version: '3.8'

services:
   postgres:
      image: postgres #<- this image come form hub.docker.com
      ports:
         - '5432:5432'
      environment:
         POSTGRES_USER: postgres
         POSTGRES_DB: review
         POSTGRES_PASSWORD: password
